#!/usr/bin/env bash

export XDG_RUNTIME_DIR=/tmp
export DISPLAY=
export INTERVENTION_CARLA_SOURCE_DIRECTORY=~/carla/CARLA_0.9.10.1_RSS
export INTERVENTION_CARLA_DIRECTORY=/tmp/CARLA_0.9.10.1_RSS-7a916435-0cf2-4e4a-a595-6bf6a6e0cb90

>&2 echo "Copying Carla simulator from ${INTERVENTION_CARLA_SOURCE_DIRECTORY} to cluster-local filesystem ${INTERVENTION_CARLA_DIRECTORY}"
rsync -r "${INTERVENTION_CARLA_SOURCE_DIRECTORY}/" "${INTERVENTION_CARLA_DIRECTORY}"
